steps:
  # Docker Compose Example
  - command: "docker-compose down"
    label: ":eagle: Stop service if it's already running"

  - wait

  - command: "docker-compose up --build --detach"
    label: ":eagle: Service up"

  - command: "docker pull stackhawk/hawkscan"
    label: ":eagle: Pull HawkScan image"

  - wait

  - label: ":eagle: Run HawkScan"
    key: hawkscan-compose
    command: |
      docker run -v $(pwd):/hawk:rw -t \
        --network nginet \
        -e API_KEY \
        stackhawk/hawkscan stackhawk.compose.yml

  - wait

  - label: ":eagle: Service down"
    command: docker-compose down

  - wait

  # Localhost Example
  - command: "docker stop nginx || echo Nevermind"
    label: ":eagle: Stop Nginx if it's already running"

  - wait

  - command: "docker run --detach --rm --publish 8000:80 --name nginx nginx"
    label: ":eagle: Run Nginx"

  - command: "docker pull stackhawk/hawkscan"
    label: ":eagle: Pull the latest HawkScan image"

  - wait

  - label: ":eagle: Run HawkScan"
    key: hawkscan-local
    command: |
      docker run -v $(pwd):/hawk:rw -t \
        --network host \
        -e API_KEY \
        stackhawk/hawkscan stackhawk.local.yml

  - wait

  - label: ":eagle: Stop Nginx"
    command: docker stop nginx


  # Remote Example
  - command: "docker pull stackhawk/hawkscan"
    label: ":eagle: Pull the latest HawkScan image"

  - wait

  - label: ":eagle: Run HawkScan"
    key: hawkscan-remote
    command: |
      docker run -v $(pwd):/hawk:rw -t \
        -e API_KEY \
        stackhawk/hawkscan stackhawk.remote.yml
